from pathlib import Path
import pandas as pd


class GenAIAssistant:
    """
    Data-grounded supply chain assistant.

    The assistant reads outputs generated by the supply chain
    intelligence agents and answers operational questions without
    inventing values.
    """

    def __init__(self):
        self.project_root = Path(__file__).resolve().parents[2]
        self.data_dir = self.project_root / "data"

        self.decision_file = (
            self.data_dir / "decision_intelligence_results.csv"
        )
        self.risk_file = (
            self.data_dir / "risk_propagation_results.csv"
        )
        self.inventory_file = (
            self.data_dir / "inventory_optimization_results.csv"
        )
        self.supplier_file = (
            self.data_dir / "supplier_risk_features.csv"
        )
        self.workforce_file = (
            self.data_dir / "workforce_intelligence_results.csv"
        )

        self.decisions = self._load_csv(self.decision_file)
        self.risks = self._load_csv(self.risk_file)
        self.inventory = self._load_csv(self.inventory_file)
        self.suppliers = self._load_csv(self.supplier_file)
        self.workforce = self._load_csv(self.workforce_file)

    def _load_csv(self, file_path):
        """Load a CSV file safely."""
        if not file_path.exists():
            return pd.DataFrame()

        return pd.read_csv(file_path)

    def _format_number(self, value, decimals=2):
        """Format numeric values for natural-language responses."""
        try:
            return f"{float(value):.{decimals}f}"
        except (ValueError, TypeError):
            return str(value)

    def warehouse_attention(self):
        """Identify the warehouse requiring the most attention."""

        if self.decisions.empty:
            return "Decision intelligence data is not available."

        row = self.decisions.sort_values(
            "Decision_Priority_Score",
            ascending=False
        ).iloc[0]

        warehouse = row["Warehouse_ID"]
        priority = row["Decision_Priority"]
        score = self._format_number(
            row["Decision_Priority_Score"]
        )
        confidence = self._format_number(
            row["Decision_Confidence"],
            0
        )

        return (
            f"{warehouse} currently needs the most attention. "
            f"Its decision priority is '{priority}' with a priority "
            f"score of {score}. Decision confidence is {confidence}%."
        )

    def explain_warehouse(self, warehouse_id):
        """Explain the decision for a specific warehouse."""

        if self.decisions.empty:
            return "Decision intelligence data is not available."

        warehouse_id = warehouse_id.upper()

        rows = self.decisions[
            self.decisions["Warehouse_ID"]
            .astype(str)
            .str.upper()
            == warehouse_id
        ]

        if rows.empty:
            return f"I could not find decision data for {warehouse_id}."

        row = rows.iloc[0]

        return (
            f"{warehouse_id} has a '{row['Decision_Priority']}' "
            f"decision priority with a score of "
            f"{self._format_number(row['Decision_Priority_Score'])}. "
            f"The dominant risk signal is "
            f"'{row['Dominant_Risk_Signal']}'. "
            f"Decision confidence is "
            f"{self._format_number(row['Decision_Confidence'], 0)}%. "
            f"Recommended action: {row['Action_Plan']}"
        )

    def risky_suppliers(self):
        """Return the highest-risk suppliers."""

        if self.suppliers.empty:
            return "Supplier risk data is not available."

        risky = self.suppliers.sort_values(
            "Risk_Score",
            ascending=False
        ).head(3)

        results = [
            "The three highest-risk suppliers are:"
        ]

        for _, row in risky.iterrows():
            results.append(
                f"- {row['Supplier_ID']}: "
                f"risk score "
                f"{self._format_number(row['Risk_Score'])}, "
                f"category {row['Risk_Category']}."
            )

        return "\n".join(results)

    def replenishment_needs(self):
        """Identify inventory requiring replenishment."""

        if self.inventory.empty:
            return "Inventory optimization data is not available."

        attention = self.inventory[
            self.inventory["Inventory_Status"].isin(
                ["Critical", "Reorder"]
            )
        ].copy()

        if attention.empty:
            return (
                "No critical or reorder inventory items "
                "were identified."
            )

        status_order = {
            "Critical": 0,
            "Reorder": 1
        }

        attention["Status_Order"] = (
            attention["Inventory_Status"]
            .map(status_order)
        )

        attention = attention.sort_values(
            "Status_Order"
        )

        results = [
            f"{len(attention)} inventory locations "
            f"require replenishment attention:"
        ]

        for _, row in attention.head(10).iterrows():
            results.append(
                f"- {row['SKU_ID']} at "
                f"{row['Warehouse_ID']}: "
                f"{row['Inventory_Status']} status, "
                f"current inventory "
                f"{self._format_number(row['Current_Inventory'], 0)}, "
                f"recommended reorder point "
                f"{self._format_number(row['Recommended_Reorder_Point'])}."
            )

        return "\n".join(results)

    def recommended_actions(self):
        """Provide the current recommended warehouse actions."""

        if self.decisions.empty:
            return "Decision intelligence data is not available."

        ordered = self.decisions.sort_values(
            "Decision_Priority_Score",
            ascending=False
        )

        results = [
            "Recommended actions:"
        ]

        for _, row in ordered.iterrows():
            results.append(
                f"- {row['Warehouse_ID']}: "
                f"{row['Action_Plan']}"
            )

        return "\n".join(results)

    def workforce_status(self):
        """Summarize workforce planning pressure."""

        if self.workforce.empty:
            return "Workforce intelligence data is not available."

        status_counts = (
            self.workforce["Workforce_Status"]
            .value_counts()
            .to_dict()
        )

        return (
            "Workforce planning summary: "
            + ", ".join(
                f"{status}={count} days"
                for status, count in status_counts.items()
            )
            + "."
        )

    def ask(self, question):
        """
        Interpret a natural-language question and return
        a data-grounded answer.
        """

        q = question.lower().strip()

        # Specific warehouse questions
        for warehouse in [
            "wh_1",
            "wh_2",
            "wh_3",
            "wh_4",
            "wh_5"
        ]:
            if warehouse in q:
                return self.explain_warehouse(
                    warehouse.upper()
                )

        # Warehouse attention
        if (
            "which warehouse" in q
            or "warehouse needs" in q
            or "warehouse attention" in q
            or "most attention" in q
        ):
            return self.warehouse_attention()

        # Supplier risk
        if (
            "supplier" in q
            and (
                "risk" in q
                or "risky" in q
                or "danger" in q
            )
        ):
            return self.risky_suppliers()

        # Inventory
        if (
            "inventory" in q
            or "replenish" in q
            or "reorder" in q
            or "stock" in q
        ):
            return self.replenishment_needs()

        # Workforce
        if (
            "workforce" in q
            or "worker" in q
            or "staff" in q
            or "employee" in q
        ):
            return self.workforce_status()

        # Actions
        if (
            "action" in q
            or "recommend" in q
            or "today" in q
            or "what should" in q
        ):
            return self.recommended_actions()

        return (
            "I can help with supply chain questions such as:\n"
            "- Which warehouse needs attention?\n"
            "- Why is WH_4 high priority?\n"
            "- Which suppliers are risky?\n"
            "- What inventory needs replenishment?\n"
            "- What are the recommended actions?\n"
            "- What is the workforce status?"
        )


if __name__ == "__main__":

    assistant = GenAIAssistant()

    print("=" * 70)
    print("AI-POWERED SUPPLY CHAIN GENAI ASSISTANT")
    print("=" * 70)

    demo_questions = [
        "Which warehouse needs attention?",
        "Why is WH_4 high priority?",
        "Which suppliers are risky?",
        "What inventory needs replenishment?",
        "What are today's recommended actions?",
        "What is the workforce status?"
    ]

    for question in demo_questions:
        print(f"\nUser: {question}")
        print(f"Assistant: {assistant.ask(question)}")