import pandas as pd
import numpy as np
from pathlib import Path


# ============================================================
# Risk Propagation Agent
# ============================================================

SUPPLIER_RISK_PATH = Path("data/supplier_risk_features.csv")
INVENTORY_PATH = Path("data/inventory_optimization_results.csv")
WORKFORCE_PATH = Path("data/workforce_intelligence_results.csv")

OUTPUT_PATH = Path("data/risk_propagation_results.csv")


def load_data():
    """Load outputs generated by previous intelligence agents."""

    supplier = pd.read_csv(SUPPLIER_RISK_PATH)
    inventory = pd.read_csv(INVENTORY_PATH)
    workforce = pd.read_csv(WORKFORCE_PATH)

    return supplier, inventory, workforce


def calculate_inventory_risk(inventory):
    """Convert inventory status into a numerical risk score."""

    risk_mapping = {
        "Healthy": 0.10,
        "Monitor": 0.40,
        "Reorder": 0.70,
        "Critical": 1.00,
    }

    inventory["Inventory_Risk"] = (
        inventory["Inventory_Status"]
        .map(risk_mapping)
        .fillna(0.50)
    )

    return inventory


def calculate_workforce_risk(workforce):
    """Convert workforce pressure into a numerical risk score."""

    risk_mapping = {
        "Adequate": 0.10,
        "Monitor": 0.50,
        "High Pressure": 1.00,
        "Underutilized": 0.10,
    }

    workforce["Workforce_Risk"] = (
        workforce["Workforce_Status"]
        .map(risk_mapping)
        .fillna(0.50)
    )

    return workforce


def calculate_supplier_risk(supplier):
    """Normalize supplier risk scores."""

    supplier["Supplier_Risk"] = (
        supplier["Risk_Score"] / 100
    )

    return supplier


def build_risk_propagation(
    supplier,
    inventory,
    workforce
):
    """
    Combine supplier, inventory and workforce signals.

    The dataset does not provide a direct supplier-to-SKU
    relationship suitable for causal modeling, so supplier
    risk is summarized at the supplier level and inventory/
    workforce risk is analyzed at operational level.
    """

    # --------------------------------------------------------
    # Supplier risk summary
    # --------------------------------------------------------

    supplier_summary = (
        supplier.groupby("Supplier_ID")
        .agg(
            Avg_Supplier_Risk=(
                "Supplier_Risk",
                "mean"
            ),
            Avg_Risk_Score=(
                "Risk_Score",
                "mean"
            ),
        )
        .reset_index()
    )

    overall_supplier_risk = (
        supplier_summary["Avg_Supplier_Risk"]
        .mean()
    )

    # --------------------------------------------------------
    # Inventory risk summary
    # --------------------------------------------------------

    inventory_summary = (
        inventory.groupby("Warehouse_ID")
        .agg(
            Avg_Inventory_Risk=(
                "Inventory_Risk",
                "mean"
            ),
            Critical_Items=(
                "Inventory_Status",
                lambda x: (x == "Critical").sum()
            ),
            Reorder_Items=(
                "Inventory_Status",
                lambda x: (x == "Reorder").sum()
            ),
        )
        .reset_index()
    )

    # --------------------------------------------------------
    # Workforce risk summary
    # --------------------------------------------------------

    workforce_summary = (
        workforce.groupby("Warehouse_ID")
        .agg(
            Avg_Workforce_Risk=(
                "Workforce_Risk",
                "mean"
            ),
            High_Pressure_Days=(
                "Workforce_Status",
                lambda x: (x == "High Pressure").sum()
            ),
            Monitor_Days=(
                "Workforce_Status",
                lambda x: (x == "Monitor").sum()
            ),
        )
        .reset_index()
    )

    # --------------------------------------------------------
    # Merge operational risk signals
    # --------------------------------------------------------

    results = inventory_summary.merge(
        workforce_summary,
        on="Warehouse_ID",
        how="left"
    )

    # --------------------------------------------------------
    # Add supplier risk exposure
    #
    # Since direct supplier-to-warehouse mapping is not
    # available in the required form, use overall supplier
    # risk as a system-level exposure.
    # --------------------------------------------------------

    results["Supplier_Risk_Exposure"] = (
        overall_supplier_risk
    )

    # --------------------------------------------------------
    # Calculate propagated risk
    #
    # Supplier:   35%
    # Inventory:  40%
    # Workforce:  25%
    # --------------------------------------------------------

    results["Propagated_Risk_Score"] = (
        results["Supplier_Risk_Exposure"] * 0.35
        + results["Avg_Inventory_Risk"] * 0.40
        + results["Avg_Workforce_Risk"] * 0.25
    ) * 100

    # --------------------------------------------------------
    # Risk classification
    # --------------------------------------------------------

    def classify_risk(score):

        if score >= 70:
            return "High"

        elif score >= 40:
            return "Medium"

        return "Low"

    results["Overall_Risk_Level"] = (
        results["Propagated_Risk_Score"]
        .apply(classify_risk)
    )

    # --------------------------------------------------------
    # Risk propagation explanation
    # --------------------------------------------------------

    def generate_explanation(row):

        risk = row["Overall_Risk_Level"]

        if risk == "High":
            return (
                "High propagated supply chain risk. "
                "Supplier exposure combined with inventory "
                "or workforce pressure requires immediate review."
            )

        elif risk == "Medium":
            return (
                "Moderate propagated risk. "
                "Monitor inventory, supplier exposure and "
                "workforce pressure closely."
            )

        return (
            "Low propagated risk. "
            "Current operational signals appear stable."
        )

    results["Risk_Propagation_Explanation"] = (
        results.apply(
            generate_explanation,
            axis=1
        )
    )

    # --------------------------------------------------------
    # Round numerical values
    # --------------------------------------------------------

    numeric_columns = results.select_dtypes(
        include=["float64", "float32"]
    ).columns

    results[numeric_columns] = (
        results[numeric_columns].round(2)
    )

    return results


def main():

    print("=" * 70)
    print("RISK PROPAGATION AGENT")
    print("=" * 70)

    supplier, inventory, workforce = load_data()

    print(
        f"Supplier records: {len(supplier)}"
    )

    print(
        f"Inventory records: {len(inventory)}"
    )

    print(
        f"Workforce records: {len(workforce)}"
    )

    # Prepare risk signals
    supplier = calculate_supplier_risk(
        supplier
    )

    inventory = calculate_inventory_risk(
        inventory
    )

    workforce = calculate_workforce_risk(
        workforce
    )

    # Build propagated risk
    results = build_risk_propagation(
        supplier,
        inventory,
        workforce
    )

    # Save results
    OUTPUT_PATH.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    results.to_csv(
        OUTPUT_PATH,
        index=False
    )

    # --------------------------------------------------------
    # Display results
    # --------------------------------------------------------

    print("\nRisk Propagation Results")
    print("-" * 70)

    print(
        results[
            [
                "Warehouse_ID",
                "Supplier_Risk_Exposure",
                "Avg_Inventory_Risk",
                "Avg_Workforce_Risk",
                "Propagated_Risk_Score",
                "Overall_Risk_Level",
            ]
        ].to_string(index=False)
    )

    print("\nRisk Level Distribution")
    print("-" * 70)

    print(
        results["Overall_Risk_Level"]
        .value_counts()
        .to_string()
    )

    print("\nOutput saved to:")
    print(OUTPUT_PATH)

    print("=" * 70)


if __name__ == "__main__":
    main()